name: Publish

on:
  push:
    branches: [ master ]

jobs:
  test-and-distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble Release Bundle
        run: |
          ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.SOME_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.SOME_KEY_PASSWORD }}

#      - name: Create service_account.json
#        run: echo '${{ secrets.GOOGLE_SERVICES_API }}' > service_account.json
#
#      - name: Deploy to Alpha
#        uses: r0adkll/upload-google-play@v1
#        with:
#          serviceAccountJson: service_account.json
#          packageName: dev.m13d.somenet
#          releaseFiles: app/build/outputs/bundle/release/app-release.aab
#          track: internal
#          whatsNewDirectory: whatsNewDirectory/
